version: "3.9"

services:
  web:
    build: .
    container_name: satellite_api
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    restart: always

  worker:
    build: .
    container_name: spei_worker
    command: python app/services/scheduler.py
    volumes:
      - .:/app
    restart: always
